Feat/pe 142/storefront header
TropixInc/w3block-ui-sdk pull request #103
Opened 2022-12-02 13:58 UTC by douglasselias

- HeaderPixway alterado para utilizar `brandText`
- Criado um `context` para tema global e tema da página de preview
- Criado componente `StorefrontPreview` que renderiza a listagem de componentes dinamicamente baseado no tipo de componente. Ex: header, banner, hero...
- Implementação parcial de listener para receber valores do tema dinamicamente

2022-12-05 13:42 UTC, yanguyt requested changes

2022-12-05 13:42 UTC, yanguyt commented on src/modules/shared/components/HeaderPixwaySDK/HeaderPixwaySDK.tsx
> +            {brandText ? (
Aqui eu faria ao contrário, se não tiver o logo deixaria o brand text

2022-12-05 13:42 UTC, yanguyt commented on src/modules/storefront/components/StorefrontPreview.tsx
> +            key={item.type}
Aqui eu nao faria com base no type não, pois podem ter dois tipos iguais no storefront o key

2022-12-05 13:42 UTC, yanguyt commented on src/modules/storefront/components/StorefrontPreview.tsx
> +    window.addEventListener('message', listener);
Eu não entendi muito o uso desse listener em cima da message

2022-12-12 13:45 UTC, douglasselias commented on src/modules/storefront/components/StorefrontPreview.tsx
> +    window.addEventListener('message', listener);
é uma implementação inicial de como o *Storefront preview* iria receber a mudança de tema, visto que ele ficaria dentro de um `iframe`

2022-12-12 20:47 UTC, yanguyt approved these changes

2022-12-13 12:32 UTC, merged