pe 143 storefront categories menu
TropixInc/w3block-ui-sdk pull request #110
Opened 2022-12-15 18:51 UTC by ingredisilva

-Categories Menu

2022-12-16 13:30 UTC, douglasselias requested changes

2022-12-16 13:30 UTC, douglasselias commented on src/modules/storefront/components/Menu.tsx
> +          </svg>
Veja se já tem algum icone nas pasta `/src/modules/shared/assets/icons` que você possa reutilizar

2022-12-16 13:30 UTC, douglasselias commented on src/modules/storefront/components/Menu.tsx
> +        <button
Precisa implementar também o dropdown, mas parece que não tem no figma, veja com o Marcus ou Marba.

Também precisa colocar um border color white
![image](https://user-images.githubusercontent.com/11854050/208106785-80d1d356-6d9b-436b-b571-3d472ec15b3f.png)

2022-12-16 13:30 UTC, douglasselias commented on src/modules/storefront/components/Menu.tsx
> +        <button
Aqui também precisa implementar o dropdown.

2022-12-16 13:30 UTC, douglasselias commented on src/modules/storefront/components/Menu.tsx
> +          <svg
Veja se já tem algum icone nas pasta `/src/modules/shared/assets/icons` que você possa reutilizar.
Uma sugestão pra simplificar um pouco o código seria colocar esse svg num componente separado, mas no mesmo arquivo.

Algo assim:
```jsx
const Icon = () => {
  return <svg>
}
```

2022-12-16 13:30 UTC, douglasselias commented on src/modules/storefront/components/Menu.tsx
> +            className="pw-hidden pw-z-10 pw-w-52 bg-white pw-rounded pw-divide-y pw-divide-white"
Essa div está como hidden, se não tem utilidade pode remover.

2022-12-16 13:30 UTC, douglasselias commented on src/modules/storefront/components/Menu.tsx
> +                <Link
Se aqui é um dropdown. não precisaria usar o Link

2022-12-16 13:30 UTC, douglasselias commented on src/modules/storefront/components/Menu.tsx
> +  const color = data.bgColor || defaultData.textColor;
Aqui teria que ter duas variaveis, uma bgColor e outra textColor, e cada variavel com sua lógica de valor default.
Está usando textColor na ausencia do bgColor, mas deveria ser na ausencia do `data.textColor`

2023-01-03 19:20 UTC, yanguyt requested changes

2023-01-03 19:20 UTC, yanguyt commented on src/modules/shared/assets/icons/arrowDownLine.svg
> +<svg width="10" height="6" viewBox="0 0 10 6" fill="none" xmlns="http://www.w3.org/2000/svg">
Ja existe um componente de arrowdown dentro dos assets, tratando de SDK reutilizar svg é sempre bom. 
No futuro a ideia é até puxar tudo de  dentro de um s3, ou qualquer outro serviço

2023-01-03 19:20 UTC, yanguyt commented on src/modules/storefront/components/Menu.tsx
> +            className="pw-border pw-border-solid pw-border-transparent pw-border-[#fff] pw-min-w-full sm:pw-min-w-max pw-h-8 pw-bg-transparent pw-rounded-3xl pw-text-base pw-px-6 pw-py-4 pw-text-cent
pw-border-transparent e pw-border-[#fff] não conflitam no propóstio não? os dois mexem com o mesmo atributo css que é o border-color

2023-01-03 19:20 UTC, yanguyt commented on src/modules/storefront/components/Menu.tsx
> +            veja todos
Faltou o translate

2023-01-03 19:20 UTC, yanguyt commented on src/modules/storefront/components/Menu.tsx
> +            Por atividade
Faltou a tradução

2023-01-03 19:20 UTC, yanguyt commented on src/modules/shared/assets/icons/arrowDownLine.svg
> +<svg width="10" height="6" viewBox="0 0 10 6" fill="none" xmlns="http://www.w3.org/2000/svg">
nome do asset arrowDown.svg

2023-01-03 19:20 UTC, yanguyt commented on src/modules/storefront/components/StorefrontPreview.tsx
>    return (
Envolve esse component dentro de um TranslatableComponent, para as traduçoes funcionarem dentro de cada componente
o Ideal era que cada parte tambem pudesse funcionar como um componente standalone, talvez sendo até melhor cada componente ser envolvido dentro de um TranslatableComponent
isso porque todos os componentes idealmente deveriam ser passiveis de serem usados por qualquer pessoa que utilize o SDK

2023-01-04 14:56 UTC, douglasselias commented on src/modules/storefront/components/Menu.tsx
> +            className="pw-border pw-border-solid pw-border-transparent pw-border-[#fff] pw-min-w-full sm:pw-min-w-max pw-h-8 pw-bg-transparent pw-rounded-3xl pw-text-base pw-px-6 pw-py-4 pw-text-cent
verdade, vou alterar

2023-01-04 14:57 UTC, douglasselias commented on src/modules/storefront/components/StorefrontPreview.tsx
>    return (
entendi, vou colocar em cada componente

2023-01-05 13:34 UTC, yanguyt requested changes

2023-01-05 13:34 UTC, yanguyt commented on src/modules/storefront/components/Menu.tsx
> +  defaultData,
Aqui é aquilo que conversamos do spread, nao precisa enviar 2... envia um só que tenham a mesma interface
<Menu data={...defaultData, ...data} />

export const Menu = ({data}) => ....

2023-01-10 13:06 UTC, yanguyt requested changes

2023-01-10 13:06 UTC, yanguyt commented on src/modules/storefront/components/Menu.tsx
> +                      <div key={category.slug} className="pw-py-4">
Aqui eu colocaria com um <a/> e ja pensaria em uma forma de colocar o href da categoria baseado na interface que tu fez

2023-01-10 13:06 UTC, yanguyt commented on src/modules/storefront/components/Menu.tsx
> +                      <div key={category.slug} className="pw-py-4">
igual tu fez no a seeAllMenu

2023-01-12 12:51 UTC, yanguyt approved these changes

2023-01-12 14:34 UTC, merged