Pe 167 banner
TropixInc/w3block-ui-sdk pull request #111
Opened 2022-12-19 18:39 UTC by douglasselias

2022-12-22 13:48 UTC, yanguyt requested changes

2022-12-22 13:48 UTC, yanguyt commented on index.html
>      <meta charset="UTF-8" />
Minha sugestão aqui é invés de fazer esse ambiente aqui para ver as mudanças, criar uma página no connect que só seja possivel acessar no ambiente de development e lá instanciar o controller ja com a lógica de construção dos componentes e os componentes. Até mesmo para QA ja poder ir validando essas tasks.

2022-12-22 13:48 UTC, yanguyt commented on src/modules/shared/components/HeaderPixwaySDK/HeaderPixwaySDK.tsx
> +          'pw-max-w-[1536px] pw-mx-auto pw-px-4',
Isso possivelmente vai quebrar varios sites que utilizam ja o HeaderPixwaySDK e se baseam no container para deixar o site com uma margem, alem de o container ser um bom ponto de quebra de layout

2022-12-22 13:48 UTC, yanguyt commented on src/modules/shared/components/HeaderPixwaySDK/HeaderPixwaySDK.tsx
> +          'pw-max-w-[1536px] pw-mx-auto pw-px-4',
o que voce pode fazer é trocar os breakpoints do tailwind, mas ainda sim voce teria que garantir que todos os sites que utilizam o SDK atualmente fizessem a mesma configuração de tailwind para os breakpoints. no caso mexer no connect e primesea

2022-12-22 13:48 UTC, yanguyt commented on src/modules/storefront/components/Banner.tsx
> +    layout === 'full_width' ? 'pw-w-full' : 'pw-max-w-[1200px]';
Aqui acredito que nao seja com o max-w-[1200px] e sim com base no container e o mesmo alinhamento do header e do resto da página

2022-12-22 13:48 UTC, yanguyt commented on src/modules/storefront/components/Banner.tsx
> +            window.open(href, '_blank')?.focus();
Aqui provavelmente vai ter uma validação no href para saber se vai mandar para fora com target _blank ou se vai ser uma navegação interna

2022-12-22 13:48 UTC, yanguyt commented on src/preview.tsx
> +const root = createRoot(document.getElementById('root')!);
Aqui aquilo que eu te falei colocar no connect até para poder pegar varias variaveis que estão dentro do providers que são necessários para o header por exemplo

2022-12-22 13:49 UTC, yanguyt commented on src/modules/shared/components/HeaderPixwaySDK/HeaderPixwaySDK.tsx
> +          'pw-max-w-[1536px] pw-mx-auto pw-px-4',
Eu particularmente não faria isso, tendo em vista tudo que ja tem no ar utilizando esse componente

2022-12-28 13:35 UTC, douglasselias commented on src/modules/shared/components/HeaderPixwaySDK/HeaderPixwaySDK.tsx
> +          'pw-max-w-[1536px] pw-mx-auto pw-px-4',
ok, vou desfazer a alteração

2022-12-28 13:42 UTC, douglasselias commented on index.html
>      <meta charset="UTF-8" />
entendi, vou fazer lá.

2022-12-28 14:40 UTC, douglasselias commented on src/modules/storefront/components/Banner.tsx
> +            window.open(href, '_blank')?.focus();
ok, vou alterar

2022-12-28 16:42 UTC, douglasselias commented on src/modules/storefront/components/Banner.tsx
> +    layout === 'full_width' ? 'pw-w-full' : 'pw-max-w-[1200px]';
ok, vou alterar

2022-12-29 01:28 UTC, yanguyt approved these changes

2022-12-29 12:04 UTC, merged