Pe 165 storefront footer
TropixInc/w3block-ui-sdk pull request #112
Opened 2022-12-20 12:55 UTC by ingredisilva

2022-12-20 18:42 UTC, douglasselias requested changes

2022-12-20 18:42 UTC, douglasselias commented on src/modules/storefront/components/Footer.tsx
> +    <>
Faltou usar a fonte `pw-font-poppins`

2022-12-22 13:59 UTC, douglasselias requested changes

2022-12-22 13:59 UTC, douglasselias commented on tailwind.config.cjs
> +      md: '768px',
Melhor não alterar esses valores, porque pode ser que algum componente dependa que o `sm` seja 768px ao invés de 640px. 
Deixe com os valores anteriores.

2022-12-22 13:59 UTC, douglasselias commented on package.json
> +    "start": "vite --port 3000"
Pode remover o comando `start` e voltar o comando `pre-release`

2022-12-22 13:59 UTC, douglasselias commented on src/modules/storefront/components/Footer.tsx
> +        </div>
O componente de cookies vai ser separado, crie outra branch pra colocar esse componente.

![image](https://user-images.githubusercontent.com/11854050/209144812-0d30198f-2dfe-49b1-ada5-873ceb27026b.png)

2022-12-22 13:59 UTC, douglasselias commented on src/modules/storefront/components/Footer.tsx
> +        </div>
Acredito que esse componente será fixo em todas as telas, mas como ele fica depois dos `cookies`, melhor colocar em outro arquivo

2022-12-22 13:59 UTC, douglasselias commented on src/modules/storefront/components/Footer.tsx
> +/* eslint-disable react/jsx-key */
Pode remover esse comentário

2022-12-22 13:59 UTC, douglasselias commented on src/modules/storefront/components/Footer.tsx
> +      // eslint-disable-next-line react/jsx-key
Pode remover esse comentário

2022-12-22 13:59 UTC, douglasselias commented on src/modules/storefront/components/Footer.tsx
> +          fill: socialNetWorkLinkSharedClassnames,
Aqui pode remover esse `fill: socialNetWorkLinkSharedClassnames`, em todos, porque as `classes` não funcionam na propriedade `fill`

2022-12-22 13:59 UTC, douglasselias commented on src/modules/storefront/components/Footer.tsx
> +        style={{ fill: color, background: '#090909', borderRadius: '50%' }}
O ideal seria usar classes o máximo possível, por exemplo o `background: '#090909' poderia ser escrito `pw-bg-[#090909]`, mas quando for alguma variável, como o `fill: color`, pode usar o `style` mesmo

2023-01-03 19:33 UTC, yanguyt requested changes

2023-01-03 19:33 UTC, yanguyt commented on src/modules/shared/assets/icons/facebook.svg
> +<path d="M9.30923 2.82142H10.5254V0.703186C10.3156 0.674321 9.59399 0.609375 8.75358 0.609375C7.00004 0.609375 5.79882 1.71234 5.79882 3.73954V5.60521H3.86377V7.97323H5.79882V13.9316H8.17129V7.97379H
Esse componente ja existe dentro dos assets, nao tem necessidade de ter outro....
facebookFilled

2023-01-03 19:33 UTC, yanguyt commented on src/modules/shared/assets/icons/linkedin.svg
> +<path d="M3.35782 1.67975C3.3576 2.12502 3.1805 2.55197 2.86548 2.86667C2.55047 3.18137 2.12334 3.35804 1.67807 3.35782C1.2328 3.3576 0.805847 3.1805 0.491147 2.86548C0.176448 2.55047 -0.000222427 2.
Esse componente ja existe dentro dos assets, nao tem necessidade de ter outro....
linkedinFilled

2023-01-03 19:33 UTC, yanguyt commented on src/modules/shared/assets/icons/twitter.svg
> +<path d="M12.896 2.94585C12.786 3.04059 12.6719 3.13076 12.5539 3.21608L12.372 3.34763L12.382 3.57191C12.3869 3.68271 12.3894 3.79624 12.3894 3.9073C12.3894 7.33907 9.77819 11.2668 5.0299 11.2668H5.0
Esse componente ja existe dentro dos assets, nao tem necessidade de ter outro....
twitterFilled

2023-01-03 19:33 UTC, yanguyt commented on src/modules/shared/assets/icons/whatsapp.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
Esse componente ja existe dentro dos assets, nao tem necessidade de ter outro....
whatsappFilled

2023-01-03 19:33 UTC, yanguyt commented on src/modules/storefront/components/Footer.tsx
> +            className="pw-flex pw-items-center pw-gap-1 pw-font-normal pw-text-sm pw-leading-[15px] pw-text-center sm:pw-mx-20 md:pw-mx-28"
md: eu acho que não existe dentro das configs de tamanho do tailwind

2023-01-04 16:42 UTC, douglasselias commented on src/modules/shared/assets/icons/facebook.svg
> +<path d="M9.30923 2.82142H10.5254V0.703186C10.3156 0.674321 9.59399 0.609375 8.75358 0.609375C7.00004 0.609375 5.79882 1.71234 5.79882 3.73954V5.60521H3.86377V7.97323H5.79882V13.9316H8.17129V7.97379H
tem mas são diferentes do que estão no design,
esses são os que já tem (iconFilled)
![image](https://user-images.githubusercontent.com/11854050/210604608-52f2c3ee-f2e0-4904-a072-0992d195bddc.png)
e esses são do figma
![image](https://user-images.githubusercontent.com/11854050/210604899-b5b369ff-b48d-4510-8504-1bfb163c60b4.png)
![image](https://user-images.githubusercontent.com/11854050/210604981-1b774c01-fdac-464e-ae8c-fa3a7a5d8e31.png)
ficaria assim no componente:
![image](https://user-images.githubusercontent.com/11854050/210605250-090844a2-72ad-4436-af21-678bca09f6ed.png)

2023-01-04 16:45 UTC, douglasselias commented on src/modules/storefront/components/Footer.tsx
> +            className="pw-flex pw-items-center pw-gap-1 pw-font-normal pw-text-sm pw-leading-[15px] pw-text-center sm:pw-mx-20 md:pw-mx-28"
verdade, vou tirar

2023-01-05 13:38 UTC, yanguyt requested changes
Os icones continuam dentro da aplicação... tem varios icones que ja tem dentro do projeto e que estão sendo inseridos novamente

2023-01-10 13:12 UTC, yanguyt requested changes

2023-01-10 13:12 UTC, yanguyt commented on src/modules/storefront/contexts/ThemeContext/ThemeContext.tsx
> +      description:
Isso daqui foi uma coisa que conversamos que vai ter que ajustar na interface, pois teremos um styleData com todos os elementos de estilo e teremos um content data com todos os elementos de texto
No figma resumidamente seria, tudo que ta na esquerda do dashboard é style e tudo que ta na direita é contentData... Acho que ja vale fazer essa divisão na interface... vou mandar em baixo a interface que fiz para cada elemento da página

2023-01-10 13:12 UTC, yanguyt commented on src/modules/storefront/contexts/ThemeContext/ThemeContext.tsx
> +      description:
a interface que fiz é basicamente essa para cada módulo da página
export interface MainModuleThemeInterface {
  name: string;
  type: ModulesType;
  id: string;
  styleData?:
    | ConfigurationModuleThemeInterface
    | HeaderModuleThemeInterface
    | FooterModuleThemeInterface
    | CategoriesModuleThemeInterface;
  contentData?: ContentData;
}

2023-01-10 13:12 UTC, yanguyt commented on src/modules/storefront/contexts/ThemeContext/ThemeContext.tsx
> +      description:
e o de cada página eu coloquei essa interface 
export interface PageModulesInterface {
  title?: string;
  slug?: string;
  modules?: MainModuleThemeInterface[];
}

2023-01-11 20:29 UTC, douglasselias commented on src/modules/storefront/contexts/ThemeContext/ThemeContext.tsx
> +      description:
mas os componentes do StorefrontPreview são diferentes dos componentes do constructor, eles precisam dos estilos e dos dados pra renderizar, acredito que ficaria mais complicado se separarasse as interfaces.

2023-01-12 18:56 UTC, yanguyt approved these changes

2023-01-12 19:04 UTC, merged