Pe 170 products list
TropixInc/w3block-ui-sdk pull request #119
Opened 2022-12-28 13:23 UTC by douglasselias

2023-01-03 19:51 UTC, yanguyt requested changes

2023-01-03 19:51 UTC, yanguyt commented on src/modules/storefront/components/Products.tsx
> +    name: data?.name !== undefined ? data.name : defaultData.name,
Essa questão do default Theme e do thema depois para mim não faz sentido.... pq sempre tem a validação e ambos na teoria podem vir undefined se o cara não setar nada.... isso para todos os componentes 
oq eu faria seria deixar a interface de ambos iguais setando fazendo um spread... {...defaultTheme, ...Theme} e ai tudo que fosse undefined de ambos eu faria uma tratativa para um valor default que podemos definir com o marquinhos. 
a situação que eu to falando é tipo, criei uma loja agora e o back não manda nada de informação para a gente, até pq não foi cadastrado, nesse caso o valor seria undefined de todas as propriedades css, e não sei qual seria o comportamento disso quando renderizasse...
Isso é só uma sugestão

2023-01-03 19:51 UTC, yanguyt commented on src/modules/storefront/components/Products.tsx
> +      data?.description !== undefined
data?.description ?? defaultData.description...
Não precisa validar se é diferente de undefined. na teoria se for null ou undefined ele atribui o que esta depois do ??

2023-01-03 19:51 UTC, yanguyt commented on src/modules/storefront/components/Products.tsx
> +      data?.category !== undefined ? data.category : defaultData.category,
Não precisa validar se é diferente de undefined. na teoria se for null ou undefined ele atribui o que esta depois do ??

2023-01-03 19:51 UTC, yanguyt commented on src/modules/storefront/components/Products.tsx
> +    price: data?.category !== undefined ? data.category : defaultData.category,
mesma coisa dos de cima

2023-01-03 19:51 UTC, yanguyt commented on src/modules/storefront/components/Products.tsx
> +const Card = ({
Eu sapararia o Card do mesmo arquivo... pois ele pode ser usado em varios outros lugares... e ai começa a ter muita reponsabilidade em um arquivo só, podendo ficar confuso

2023-01-03 19:51 UTC, yanguyt commented on src/modules/storefront/components/Products.tsx
> +  const SliderProducts = () => {
eu separaria o Slider products do mesmo arquivo, pois ele pode ser usado de outras maneiras depois, não só recebendo cards mas recebendo outras coisas e podendo ser configuravel para outras coisas, alem de desacoplar esse arquivo que ja esta com algumas coisas

2023-01-03 19:51 UTC, yanguyt commented on src/modules/storefront/components/Products.tsx
> +const fetchProductsByTagAndOrder = async (
Se isso no futuro for a lógica de chamada na api eu faria tambem em outro arquivo, esse ja esta totalmente acoplado com outros arquivos, seguindo padrao que o SDK utiliza, colocando a chamada dentro de um hook e tudo mais onde retorna a api... no caso nao precisa por enquanto, mas ja é possivel, até colocar dentro de um useQuery para ai depois só trocar esse código para a chamada da api

2023-01-04 18:51 UTC, douglasselias commented on src/modules/storefront/components/Products.tsx
> +  const SliderProducts = () => {
entendi, mas eu vejo de outra forma. o próprio componente de slider (`swiper`) já seria essa abstração. porque esse SliderProducts está com os estilos e breakpoints específicos dele, acredito que ficaria um pouco complexo desacoplar isso

2023-01-05 13:40 UTC, yanguyt requested changes

2023-01-09 12:34 UTC, yanguyt approved these changes
Eu acho que vale voce dar uma lida nesse arquivo aqui.
https://blog.logrocket.com/types-vs-interfaces-in-typescript/ 
Acho que type é bom de usar mas não como forma de receber props como voce esta usando... não está errado mas eu faria com interface. se der da uma lida no link que eu te mandei

2023-01-09 13:59 UTC, merged