feat: create cookies component
TropixInc/w3block-ui-sdk pull request #126
Opened 2023-01-03 19:19 UTC by douglasselias

2023-01-03 19:59 UTC, gislainy commented on src/modules/storefront/components/Cookies.tsx
> +    data?.privacyPolicyLinkColor || defaultData.privacyPolicyLinkColor;
```suggestion
 const { cookiesBgColor, cookiesTextColor, cookiesButtonBgColor, cookiesButtonTextColor, privacyPolicyLinkColor} = Object.assign({}, defaultData, data || {});
```

2023-01-03 20:01 UTC, yanguyt requested changes

2023-01-03 20:01 UTC, yanguyt commented on src/modules/storefront/components/Cookies.tsx
> +            Política de privacidade.
Faltou a tradução

2023-01-03 20:01 UTC, yanguyt commented on src/modules/storefront/components/Cookies.tsx
> +          Estou ciente
faltou a tradução

2023-01-03 20:02 UTC, gislainy commented on src/modules/storefront/components/Cookies.tsx
> +};
```suggestion


export type CookiesDefault = {
  cookiesBgColor: string;
  cookiesTextColor: string;
  cookiesButtonBgColor: string;
  cookiesButtonTextColor: string;
  privacyPolicyLinkColor: string;
};

export type CookiesData = CookiesDefault & {  privacyPolicyLink?: string;  disclaimer?: string; };

```

2023-01-03 20:04 UTC, gislainy commented on src/modules/storefront/components/StorefrontPreview.tsx
> +      Copyright 2022 - [web/lock]
```suggestion
      Copyright {new Date().getFullYear()} - [web/lock]
```

2023-01-03 20:05 UTC, gislainy requested changes

2023-01-03 20:05 UTC, gislainy commented on src/modules/storefront/components/StorefrontPreview.tsx
> +      Copyright 2022 - [web/lock]
```suggestion
      Copyright {new Date().getFullYear()} - [web/lock]
```

2023-01-05 12:47 UTC, yanguyt approved these changes

2023-01-05 13:42 UTC, gislainy approved these changes

2023-01-05 14:56 UTC, merged