Pe 172 storefront renderer (theme listener)
TropixInc/w3block-ui-sdk pull request #127
Opened 2023-01-09 12:37 UTC by douglasselias

Branch criada a partir da `products` refatorada

2023-01-09 13:10 UTC, gislainy commented on src/modules/shared/components/Card/Card.tsx
> +          className={`pw-w-full pw-border-b pw-border-white pw-py-2 pw-font-medium pw-rounded-[48px] product-card-button`}
```suggestion
          className="pw-w-full pw-border-b pw-border-white pw-py-2 pw-font-medium pw-rounded-[48px] product-card-button"
```

2023-01-09 13:11 UTC, gislainy commented on src/modules/shared/components/Card/Card.tsx
> +      )}
```suggestion
      {config.showCardDescription && product.description?.trim() (
        <p className="pw-text-[#7E7E7E]">{product.description}</p>
      )}
```

2023-01-09 13:17 UTC, gislainy commented on src/modules/storefront/components/Products.tsx
> +  );
```suggestion
  const gridMaxItemsTotal = itemsPerLine * numberOfLines;
  const carouselMaxItems = 12;
  const carouselSize =   layoutProducts === 'grid' ? gridMaxItemsTotal : carouselMaxItems;
  const clampedProducts = products?.slice(
    0,
   carouselSize
  );
```

2023-01-09 13:17 UTC, gislainy commented on src/modules/storefront/components/Products.tsx
> +    });
Faltou um .catch

2023-01-09 13:23 UTC, gislainy commented on src/modules/storefront/components/Banner.tsx
> +          <SwiperSlide key={JSON.stringify(slide)}>
Não entendi porque estava assim antes. Isso quebra totalmente a proposta de ter a key nesse elemento. 

A pergunta é, não há um identificador único no elemento do slide?

2023-01-09 18:05 UTC, douglasselias commented on src/modules/shared/components/Card/Card.tsx
> +      )}
no dashboard tem limite de 200 caracteres para a descrição.
com 200 caracteres ficaria assim:
![image](https://user-images.githubusercontent.com/11854050/211376707-8ca3614c-c15f-4862-8028-90d32a872541.png)

2023-01-09 18:08 UTC, douglasselias commented on src/modules/storefront/components/Banner.tsx
> +          <SwiperSlide key={JSON.stringify(slide)}>
hm, acho que dá pra usar o title

2023-01-10 13:29 UTC, yanguyt requested changes

2023-01-10 13:29 UTC, yanguyt commented on src/modules/shared/components/Card/Card.tsx
> +      )}
eu acho que isso vale falar com o marquinhos, tendo em vista que é um grid, nao limitar tamanho do card pode transformar o grid em uma coisa muito feia.... eu colocaria um truncate depois de 2 linhas e setaria o tamanho da parte de texto na mão, assim não teria variação nos tamanhos do card

2023-01-10 13:29 UTC, yanguyt commented on src/modules/storefront/components/Banner.tsx
>            <video
nesse caso não tenho certeza se funcionaria legal, por isso vale o teste

2023-01-10 13:29 UTC, yanguyt commented on src/modules/storefront/components/Products.tsx
> +export type CardConfig = {
eu particularmente não gosto de todas os types e interfaces dentro do mesmo documento que esta escrito código tsx, tendo em vista que é compartilhado por todo código... isso faz com que quem va dar manunten'ão tem que descobri que os types/interfaces estão dentro de um arquivo que tem multiplas responsabilidades... eu colocaria em outro lugar seguindo  o padrão do projeto onde normalmente dentro de cada módulo tem uma pasta interface com todas as interfaces compartilhadas normalmente por varios lugares

2023-01-11 15:56 UTC, douglasselias commented on src/modules/shared/components/Card/Card.tsx
> +      )}
coloquei o limite de duas linhas no nome e descrição do produto
![image](https://user-images.githubusercontent.com/11854050/211848968-5a7bb9db-f1fb-489c-a01d-7f2e6cc60c0d.png)

2023-01-12 13:11 UTC, yanguyt approved these changes

2023-01-12 16:42 UTC, merged