fix(passAdjusts)many adjusts on pass
TropixInc/w3block-ui-sdk pull request #132
Opened 2023-01-24 19:37 UTC by marcoaschmidt

2023-01-24 20:35 UTC, gislainy commented on src/modules/core/providers/W3blockSDKGeneralConfigProvider/W3blockSDKGeneralConfigProvider.tsx
> +    [isProduction, launchDarklyKey]
O correto é o ambiente enviar a variável do lauch darky já que estamos falando de SDK.

Caso o ambiente não mande, deveria ter um erro de uso ou não ter lunchDarky.

Isso obriga a todos que usam seguir a configuração do lauchDarkly da weblock e foge do princípio que estamos entregando um sdk.

2023-01-24 20:35 UTC, gislainy commented on src/modules/tokens/components/WalletTokenCard/WalletTokenCard.tsx
> +  const hasPass = publicTokenResponse?.data.group.collectionPass && pass;
```suggestion
  const hasPass = publicTokenResponse?.data?.group?.collectionPass && pass;
```

2023-01-24 20:35 UTC, gislainy commented on src/modules/tokens/components/WalletTokenCard/WalletTokenCard.tsx
> +      collectionId={publicTokenResponse?.data.group.collectionId || ''}
```suggestion
      collectionId={publicTokenResponse?.data?.group?.collectionId || ''}
```

2023-01-26 18:35 UTC, yanguyt requested changes

2023-01-26 18:35 UTC, yanguyt commented on src/modules/core/providers/W3blockSDKGeneralConfigProvider/W3blockSDKGeneralConfigProvider.tsx
> +          ? '636e4bf4ec20a110ee5be93d'
é então isso daqui não pode ocorrer eu acho, mesma coisa que a gis falou... isso daqui fica aberto para quem quiser pegar essa key e usar da forma que quiser... não seria ideal deixar assim a mostra, mesmo que só em dev

2023-01-26 18:35 UTC, yanguyt commented on src/modules/pass/hooks/useGetQRCodeSecret.ts
> +      enabled: validator.isUUID(benefitId) && validator.isUUID(editionNumber),
esse EditionNumber é um UUID??

2023-01-26 18:47 UTC, yanguyt approved these changes

2023-01-26 18:51 UTC, merged