feat: create image plus text component
TropixInc/w3block-ui-sdk pull request #137
Opened 2023-02-08 20:52 UTC by douglasselias

2023-02-10 00:15 UTC, yanguyt approved these changes

2023-02-10 00:16 UTC, yanguyt requested changes

2023-02-10 00:16 UTC, yanguyt commented on src/modules/storefront/components/ImagePlusText.tsx
> +        <div className="pw-w-full pw-h-full pw-grid pw-place-items-center">
eu acho que esse pw-full tanto no width quanto no height vai dar ruim... eu travaria com um tamanho maximo... voce chegou a testar para ver oq acontece quando voce sobe uma imagem

2023-02-13 14:41 UTC, douglasselias commented on src/modules/storefront/components/ImagePlusText.tsx
> +        <div className="pw-w-full pw-h-full pw-grid pw-place-items-center">
agora coloquei o tamanho maximo baseado no figma

2023-02-13 17:17 UTC, yanguyt approved these changes

2023-02-13 18:05 UTC, merged