feat(pe-71): token details page
TropixInc/w3block-ui-sdk pull request #15
Opened 2022-09-02 20:22 UTC by schleu

2022-09-09 16:09 UTC, Percegaroli commented on src/modules/tokenization/hooks/useDialogController.ts
> +export default useModalController;
Pra todos os hooks desse modulo faltou adaptar ao padrão desse projeto (uma pasta pra cada hook, um arquivo index fazendo apenas a exportação)

2022-09-09 16:11 UTC, Percegaroli commented on src/modules/tokenization/components/DisplayCards/PublicTokenEditionCard/index.tsx
> +      </ul>
Faltou adicionar os prefixos de classe pw-

2022-09-09 16:12 UTC, Percegaroli commented on src/modules/tokenization/components/DisplayCards/PublicTokenInformationDisplayCard/index.tsx
> +        <div className="flex flex-col gap-y-8">
Faltou adicionar os prefixo de classe pw-

2022-09-09 16:13 UTC, Percegaroli commented on src/modules/tokenization/components/DisplayCards/CategoryDisplayCard/index.tsx
> +          'grid grid-cols-1 gap-y-4 sm:grid-cols-2 sm:gap-y-8 gap-x-2.5',
Faltou adicionar os prefixos de classe pw-

2022-09-09 16:14 UTC, Percegaroli commented on src/modules/tokenization/components/DisplayCards/CategoryDisplayCard/index.tsx
> +export default CategoryDisplayCard;
No padrão desse projeto o arquivo index deveria apenas exportar o codigo de outro(s) arquivo(s)

2022-09-09 16:14 UTC, Percegaroli commented on src/modules/tokenization/components/DisplayCards/DisplayCardBase/index.tsx
> +export default DisplayCardBase;
No padrão desse projeto o arquivo index deveria apenas exportar o codigo de outro(s) arquivo(s)

2022-09-09 16:15 UTC, Percegaroli commented on src/modules/tokenization/components/DisplayCards/OffpixButtonBase/OffpixButtonBase.tsx
> +export default OffpixButtonBase;
o export do arquivo deve ser apenas nomeado, sem export default

2022-09-09 16:16 UTC, Percegaroli commented on src/modules/tokenization/components/DisplayCards/OffpixButtonBase/index.ts
> +export * from './OffpixButtonBase';
Isso está exportando apenas as interfaces e types do arquivo, pois o componente em si do arquivo está com export default
O ideal seria padronizar as exportações pra caso o componente precise ser exportado isolado a maneira de importar para quem for consumir a lib seja igual para todos os componentes

2022-09-09 16:16 UTC, Percegaroli commented on src/modules/tokenization/components/DisplayCards/PublicTokenInformationDisplayCard/index.tsx
> +export default PublicTokenInformationDisplayCard;
No padrão desse projeto o arquivo index deveria apenas exportar o codigo de outro(s) arquivo(s) e o componente deve seguir o padrão de export nomeado (sem export default)

2022-09-09 16:18 UTC, Percegaroli commented on src/modules/tokenization/components/SmartDisplay/EditionFieldDisplay/index.tsx
> +export default EditionFieldDisplay;
No padrão desse projeto o arquivo index deveria apenas exportar o codigo de outro(s) arquivo(s) e o componente deve seguir o padrão de export nomeado (sem export default)

2022-09-09 16:18 UTC, Percegaroli commented on src/modules/tokenization/components/SmartDisplay/ImageFieldDisplay/index.tsx
> +        <div className="flex flex-col gap-y-0.5 text-xs leading-[14px] text-[#676767]">
faltou os prefixos pw- para as classanames

2022-09-09 16:18 UTC, Percegaroli commented on src/modules/tokenization/components/SmartDisplay/ImageFieldDisplay/index.tsx
> +export default ImageFieldDisplay;
No padrão desse projeto o arquivo index deveria apenas exportar o codigo de outro(s) arquivo(s) e o componente deve seguir o padrão de export nomeado (sem export default)

2022-09-09 16:18 UTC, Percegaroli commented on src/modules/tokenization/components/SmartDisplay/RFIDFieldDisplay/index.tsx
> +                .padStart(2, '0')}`}
Faltou os prefixos de classname pw-

2022-09-09 16:19 UTC, Percegaroli commented on src/modules/tokenization/components/SmartDisplay/RFIDFieldDisplay/index.tsx
> +export default RFIDFieldDisplay;
No padrão desse projeto o arquivo index deveria apenas exportar o codigo de outro(s) arquivo(s) e o componente deve seguir o padrão de export nomeado (sem export default)

2022-09-09 16:19 UTC, Percegaroli commented on src/modules/tokenization/components/SmartDisplay/TextFieldDisplay/index.tsx
> +export default TextFieldDisplay;
No padrão desse projeto o arquivo index deveria apenas exportar o codigo de outro(s) arquivo(s) e o componente deve seguir o padrão de export nomeado (sem export default)

2022-09-09 16:34 UTC, Percegaroli commented on src/modules/tokens/components/PublicPageQRCode/index.tsx
> +  }${publicPagePath}`;
O SDK em si não terá variaveis de ambiente, pois ele é uma biblioteca. Esse valor precisa vir de alguma configuração no foodbuster
eu te passei uma env no discord pra vc colocar no foodbusters, mas será necessário alterar o provider de configuração do sdk pra incluir essa url
Olhar como foi feito nesse commit : https://github.com/TropixInc/w3block-ui-sdk/pull/11/commits/cbe45eff2a8af2b5b5f5e0998158b4f8001085e8

2022-09-09 16:38 UTC, Percegaroli commented on src/modules/tokens/components/PublicPageQRCode/index.tsx
> +  }${publicPagePath}`;
Esqueci de comentar também rsrs
No caso a url base precisa apontar pra pixway, por que a pagina publica do token se encontra lá

2022-09-15 16:51 UTC, Percegaroli requested changes
É necessário criar uma pagina no foodbusters utilizando o template criado nesse PR (usar a rota que foi adicionada no PixwayAPPRoutes)

Paralelo ao desenvolvimento dessa task, foi criado um componente chamado `TokenLayoutBase`, responsável por adicionar os demais elementos da pagina (header, menu lateral e footer). É necessário adicionar ele no template (se tiver duvida olhar como foi feito na pagina de listagem de tokens).

2022-09-15 16:51 UTC, Percegaroli commented on src/modules/tokens/enums/tokenizationFieldTypes.ts
> +}
A pasta possui dois arquivos com o mesmo nome, mudando apenas o case. Está dando erro no build por causa disso.
É importante se atentar a esses detalhes quando fizer merge

2022-09-16 13:18 UTC, Percegaroli commented on src/modules/tokens/enums/tokenizationFieldTypes.ts
> +}
Esse arquivo não pode ficar assim. A pasta possuí dois arquivos com o mesmo nome (mudando apenas capitalização) que está dando erro no build

![image](https://user-images.githubusercontent.com/56946412/190648049-523502f9-353e-422d-ae80-902a2fb93123.png)

2022-09-16 13:18 UTC, Percegaroli requested changes
ainda está dando erro no build

![image](https://user-images.githubusercontent.com/56946412/190648127-f8ebf03e-4d80-4d12-905f-cf0779916abf.png)

2022-09-28 12:36 UTC, yanguyt requested changes

2022-09-28 12:36 UTC, yanguyt commented on src/modules/tokens/components/QRCodeModal/QRCodeModal.tsx
> +          : 'pw-p-[30px_28px] lg:pw-p-[42px_40px_53px]'
Isso daqui nao faz sentido, primeiro que o tailwind tem as tags de controle de tamanho e acredito que a sm:pw-... ja resolveria esse problema sem ter que usar ${...}
e outro pronto é se o pw-p-[30px_28px] está nos dois, pode deixar no className de todo mundo

2022-09-28 12:36 UTC, yanguyt commented on src/modules/tokens/components/QRCodeModal/QRCodeModal.tsx
> +        className={`pw-font-semibold pw-leading-[19px] pw-text-[#333333] ${windowDimensions.height < 768 ? 'pw-mb-[30px]' : 'pw-mb-[30px] lg:pw-mb-10'
Mesma coisa aqui

2022-09-28 12:36 UTC, yanguyt commented on src/modules/tokens/components/QRCodeModal/QRCodeModal.tsx
> +          ${windowDimensions.height < 768 ? 'pw-gap-y-[16px]' : 'pw-gap-y-[22px]'}`}
mesma coisa

2022-09-28 15:23 UTC, schleu commented on src/modules/tokens/enums/tokenCreationSteps.ts
> +  CONTRACT = 1,
O arquivo não estava sendo usado, então exclui.

2022-09-28 16:47 UTC, merged