feat(TK-1111): implement request information KYC
TropixInc/w3block-ui-sdk pull request #151
Opened 2023-03-08 13:15 UTC by fernando-pascoal

2023-03-08 17:32 UTC, gislainy commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +const _FormCompleteKYCWithoutLayout = ({ userId }: Props) => {
Não sei qual padrão você usam de variável, mas não vejo necessidade dessa variável começar com underscore.

2023-03-08 17:33 UTC, gislainy commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +    if (tenantInputs.data?.data && userId)
```suggestion
    if (tenantInputs.data?.data?.length > 0 && userId)
```

2023-03-08 17:33 UTC, gislainy commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +        userId: userId,
```suggestion
        userId,
```

2023-03-08 17:34 UTC, gislainy commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +    const arrayValues = Object.values(dynamicValues);
```suggestion
    const documents  = Object.values(dynamicValues);
```

2023-03-08 17:36 UTC, gislainy commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +  };
```suggestion
  const onSubmit = () => {
    const dynamicValues = dynamicMethods.getValues();
    if (tenantInputs.data?.data?.length && userId) {
      const { contextId } = tenantInputs.data.data[0];
      mutate({
        tenantId,
        contextId,
        userId,
        documents: {
          documents: Object.values(dynamicValues),
        },
      });
    }
  };
```

2023-03-08 17:37 UTC, gislainy commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +  }, [dynamicMethods.watch()]);
```suggestion
  useEffect(() => {
    const values = dynamicMethods.getValues();
    const documents = Object.values(values);
    const isVallidForm = documents.every((obj) => obj !== undefined);
    setValidForm(isVallidForm)
  }, [dynamicMethods.watch()]);
```

2023-03-08 17:41 UTC, gislainy commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +          Continuar
Falta a tradução

2023-03-08 17:42 UTC, gislainy commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +                  : ''
Recomendo isso ser uma função de pegar o documento do array. Esse código está duplicado tanto no campo de assetId e value. 

algo do tipo

```typescript 
function getDocumentByInputId(inputId: string) {
     return documents?.data.find((doc) => doc.inputId === inputId)
}
```

2023-03-08 17:43 UTC, gislainy commented on src/modules/auth/components/SignUpFormWithoutLayout/SignUpFormWithoutLayout.tsx
> +    }
```suggestion
      return window?.navigator?.language === 'pt-BR'
        ? I18NLocaleEnum.PtBr
        : I18NLocaleEnum.En;
    
```

2023-03-08 17:44 UTC, gislainy commented on src/modules/auth/components/SignUpFormWithoutLayout/SignUpFormWithoutLayout.tsx
> +    const getMethodsValue = methods.getValues();
```suggestion
    const user = methods.getValues();
```

2023-03-08 17:45 UTC, gislainy commented on src/modules/auth/components/SignUpFormWithoutLayout/SignUpFormWithoutLayout.tsx
> +    const getMethodsValue = methods.getValues();
O nome anterior não está claro o que significa. Acredito que seja user, né?

2023-03-08 17:45 UTC, gislainy commented on src/modules/auth/components/SignUpTemplate/SignUpTemplate.tsx
> +    }
```suggestion
      return window?.navigator?.language === 'pt-BR'
        ? I18NLocaleEnum.PtBr
        : I18NLocaleEnum.En;
    
```

2023-03-08 17:45 UTC, gislainy commented on src/modules/auth/templates/CompleteKYCTemplateSDK/CompleteKYCTemplateSDK.tsx
> +  contentType?: contentTypeEnum;
```suggestion
  contentType?: ContentTypeEnum;
```

2023-03-08 17:46 UTC, gislainy commented on src/modules/auth/templates/CompleteKYCTemplateSDK/CompleteKYCTemplateSDK.tsx
> +import { contentTypeEnum } from '../../../poll';
```suggestion
import { ContentTypeEnum } from '../../../poll';
```

2023-03-08 17:46 UTC, gislainy commented on src/modules/auth/templates/CompleteKYCTemplateSDK/CompleteKYCTemplateSDK.tsx
> +import { contentTypeEnum } from '../../../poll';
Precisa alterar o nome dessa enum no projeto. Sempre começa com letra maiúscula por convenção.

2023-03-08 17:47 UTC, gislainy commented on src/modules/auth/templates/CompleteKYCTemplateSDK/CompleteKYCTemplateSDK.tsx
> +      if (profile.data.kycStatus !== 'pending') {
Use a Enum que o SDK retorna. Não recomendo usar valores de enum assim solto, pois qualquer alteração vinda do SDK pode quebrar esse código e não percebemos.

2023-03-08 17:48 UTC, gislainy commented on src/modules/auth/templates/CompleteKYCTemplateSDK/CompleteKYCTemplateSDK.tsx
> +          FAQContext={FAQContext}
```suggestion
          faqContext={FAQContext}
```

2023-03-08 17:48 UTC, gislainy commented on src/modules/auth/templates/CompleteKYCTemplateSDK/CompleteKYCTemplateSDK.tsx
> +          FAQContext={FAQContext}
Nome de atributo deve seguir o padrão camelCase. Acredito que já estava assim antes, porém ficou errado.

2023-03-08 17:48 UTC, gislainy commented on src/modules/auth/templates/CompleteKYCTemplateSDK/CompleteKYCTemplateSDK.tsx
> +              <FormCompleteKYCWithoutLayout userId={profile?.data.id} />
```suggestion
              <FormCompleteKYCWithoutLayout userId={profile?.data?.id} />
```

2023-03-08 17:49 UTC, gislainy commented on src/modules/auth/templates/CompleteKYCTemplateSDK/CompleteKYCTemplateSDK.tsx
> +  return profile ? (
```suggestion
  return profile?.data?.id ? (
```

2023-03-08 17:51 UTC, gislainy commented on src/modules/core/providers/W3blockApiProvider/W3blockApiProvider.tsx
> +  w3blockDirectoryApiUrl: string;
Pode remover isso, não existirá mais esse projeto.

2023-03-08 17:51 UTC, gislainy commented on src/modules/core/providers/W3blockSDKGeneralConfigProvider/W3blockSDKGeneralConfigProvider.tsx
> +          w3blockDirectoryApiUrl={api.directory ?? ''}
Pode remover

2023-03-08 17:51 UTC, gislainy commented on src/modules/shared/components/SmartInputs/InputCpf/index.tsx
> +
```suggestion
```

2023-03-08 17:52 UTC, gislainy commented on src/modules/shared/components/SmartInputs/InputFile/index.tsx
> +      const type = acceptedFiles[0].type.includes('pdf')
```suggestion
      const type = acceptedFiles[0]?.type?.includes('pdf')
```

2023-03-08 17:53 UTC, gislainy commented on src/modules/shared/components/SmartInputs/InputFile/index.tsx
> +    if (file && assets?.data.id) {
```suggestion
    if (file && assets?.data?.id) {
```

2023-03-08 17:53 UTC, gislainy commented on src/modules/shared/components/SmartInputs/InputFile/index.tsx
> +    if (isSuccess && data && assets) {
```suggestion
    if (isSuccess && data && assets?.data?.id) {
```

2023-03-08 17:53 UTC, fernando-pascoal commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +const _FormCompleteKYCWithoutLayout = ({ userId }: Props) => {
Sinceramente, eu não sei o motivo, mas esse é o padrão que já esta no projeto e o Yan me pediu pra seguir.

2023-03-08 17:53 UTC, gislainy commented on src/modules/shared/components/SmartInputs/InputFile/index.tsx
> +      return file && file.name ? file?.name : 'Selecione um arquivo';
Tradução

2023-03-08 17:55 UTC, gislainy commented on src/modules/shared/components/SmartInputs/InputPhone/index.tsx
> +              : () => onChangeInvalidNumber(false)
```suggestion
            inputValue
              ? isValidPhoneNumber(inputValue)
                ? () => onChangeInvalidNumber(false)
                : () => onChangeInvalidNumber(true)
              : () => onChangeInvalidNumber(false)
```

2023-03-08 17:56 UTC, gislainy commented on src/modules/shared/components/SmartInputs/InputPhone/index.tsx
> +              : () => onChangeInvalidNumber(false)
```suggestion
            inputValue  
              ? () => onChangeInvalidNumber(!isValidPhoneNumber(inputValue))
              :  () => onChangeInvalidNumber(false)
```

2023-03-08 17:57 UTC, gislainy commented on src/modules/shared/components/SmartInputs/InputUrl/index.tsx
> +    if (value) {
```suggestion
    if (isUrl(value)) { // usar a lib do validator, tem no projeto.
```

2023-03-08 17:58 UTC, gislainy commented on src/modules/shared/components/SmartInputs/InputUrl/index.tsx
> +const InputUrl = ({ label, name, docValue }: InputUrlProps) => {
Precisa adicionar verificar se a URL é valida, use a `isUrl` do validator que a mesma que uso no backend.

2023-03-08 17:58 UTC, gislainy commented on src/modules/shared/components/SmartInputsController/index.tsx
> +}
```suggestion
interface SmartProps {
  type: DataTypesEnum;
  label: string;
  name: string;
  value?: string;
  assetId?: string | null;
}
```

2023-03-08 17:59 UTC, gislainy commented on src/modules/shared/enums/KYCTypes.ts
> +}
Recomendo você usar o que retorna diretamente no SDK do ID, assim você sempre irá manter a compatibilidade.

2023-03-08 17:59 UTC, gislainy commented on src/modules/shared/enums/PixwayAPIRoutes.ts
> +  GET_SIGNED_CLOUDINARY_URL = '/users-documents/{tenantId}/generate-signature',
```suggestion
```

2023-03-08 17:59 UTC, gislainy commented on src/modules/shared/enums/W3blockAPI.ts
> +  DIRECTORY,
```suggestion
```

2023-03-08 17:59 UTC, gislainy commented on src/modules/shared/hooks/useAxios/useAxios.ts
> +    [W3blockAPI.DIRECTORY, apisUrl.w3blockDirectoryApiUrl],
```suggestion
```

2023-03-08 18:01 UTC, gislainy commented on src/modules/shared/hooks/useUploadFileToCloudinary/useUploadFileToCloudinary.ts
> +          }/${'image/'}upload`,
```suggestion
          }/image/upload`,
```

2023-03-08 18:01 UTC, gislainy commented on src/modules/shared/utils/getValidationsTypesForSignup.ts
> +              .required('insira um email valido'),
tradução

2023-03-08 18:02 UTC, gislainy commented on src/modules/shared/utils/getValidationsTypesForSignup.ts
> +export const getValidationsTypesForSignup = (
falta tradução para todos os type

2023-03-08 18:04 UTC, gislainy reviewed
@fernando-pascoal deixei alguns comentários, depois veja eles.

2023-03-08 18:11 UTC, fernando-pascoal commented on src/modules/auth/templates/CompleteKYCTemplateSDK/CompleteKYCTemplateSDK.tsx
> +          FAQContext={FAQContext}
Esse atributo já estava com letra maiuscula mesmo, não sei se eu alterar pode acabar mexendo em outras aplicações que usam esse componente

2023-03-15 17:14 UTC, yanguyt requested changes
Eu acho que o controller dos inputs voce poderia ter feito de forma muito mais simples ao inves de criar um arquivo para cada .... tendo em vista que tirando o upload de documento, o resto eram apenas inputs com mascaras e validações

2023-03-15 17:14 UTC, yanguyt commented on src/modules/shared/components/SmartInputs/InputEmail/index.tsx
> +interface InputCPFProps {
Troca o nome dessa props para nao confundir...

2023-03-15 17:14 UTC, yanguyt commented on src/modules/auth/hooks/useGetReasonsRequiredReview/useGetReasonsRequiredReview.ts
> +  return usePrivateQuery([tenantId, userId, contextId], async () => {
Coloca opção para só fazer a request se tiver tenantId, userId e contextId.... {enabled: ....}

2023-03-15 17:14 UTC, yanguyt commented on src/modules/shared/hooks/useGetTenantContext/useGetTenantContext.ts
> +  return useQuery([], async () => {
coloca uma validação para nao fazer request para undefined {enabled:  ....}

2023-03-15 17:14 UTC, yanguyt commented on src/modules/shared/hooks/useGetTenantContext/useGetTenantContext.ts
> +  return useQuery([], async () => {
outra coisa a key esta vazia... isso pode dar problemas iguais aos que voce ja teve de a request ficar gravada no cache e confundir.... coloca. o nome da rota e o tenantIdcomo key

2023-03-15 17:14 UTC, yanguyt commented on src/modules/shared/hooks/useGetTenantInputs/useGetTenantInputsBySlug.ts
> +  return usePrivateQuery([], async () => {
Coloca enabled baseade no companyId e a key do useQUery esta vazia.... pode dar problema coloque alguma coisa relevante para salvar no cache

2023-03-15 17:14 UTC, yanguyt commented on src/modules/shared/hooks/useGetUsersDocuments/useGetUsersDocuments.ts
> +  return usePrivateQuery([userId, contextId], async () => {
eu aqui colocaria mais alguma coisa para nao ter chance de duplicidade na key... tipo o nome da rota e tal

2023-03-15 17:14 UTC, yanguyt commented on src/modules/shared/hooks/useGetUsersDocuments/useGetUsersDocuments.ts
> +    );
Esta faltando colocar o enabled validando se nada esta como undefined

2023-03-15 17:14 UTC, yanguyt commented on src/modules/shared/hooks/usePostUsersDocuments/usePostUsersDocuments.ts
> +    [],
Mesma coisa do resto a key esta vazia, coloque algo que identifique essa key para esta chamada

2023-03-15 17:14 UTC, yanguyt commented on src/modules/shared/hooks/useUploadFileToCloudinary/useUploadFileToCloudinary.ts
> +    [],
Key vazia....

2023-03-15 17:14 UTC, yanguyt commented on src/modules/shared/hooks/useUploadFileToCloudinary/useUploadFileToCloudinary.ts
> +          // @ts-ignore
ts-ignore me preocupa

2023-03-15 17:14 UTC, yanguyt commented on src/modules/shared/hooks/useUploadFileToCloudinary/useUploadFileToCloudinary.ts
> +          // @ts-ignore
ts-ignore me preocupa

2023-03-15 17:30 UTC, fernando-pascoal commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +          documents: Object.values(dynamicValues),
Sim, o back esta esperando um array

2023-03-15 17:32 UTC, fernando-pascoal commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +  }, [dynamicMethods.watch()]);
Nessa caso eu fiz assim, pq não consegui validar os campos, por conta de ser dinamico eu não consegui validar todos os campos, então não conseguia habilitar e desabilitar o button de Continuar

2023-03-15 17:39 UTC, fernando-pascoal commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +      {/*@ts-ignore*/}
![image](https://user-images.githubusercontent.com/96430308/225396040-d480f63d-3b2f-4ca6-a7af-f8f82abd8025.png)

Neste caso eu usei o ts ignore porque ele fica o tempo todo reclamando que o objeto pode ser nulo, já fiz algumas validações e ele não "aceita"

2023-03-15 17:41 UTC, fernando-pascoal commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +          {/*@ts-ignore*/}
![image](https://user-images.githubusercontent.com/96430308/225396258-3163590e-8df2-46d0-a4f9-93f1f822144f.png)

Nesse caso eu usei o ts ignore porque o back ta trazendo a tipagem do inputIds como array<any>, mas na verdade ele é um array<string>, e ai fica dando erro de tipagem no item do map

2023-03-15 17:56 UTC, fernando-pascoal commented on src/modules/shared/hooks/useUploadFileToCloudinary/useUploadFileToCloudinary.ts
> +          // @ts-ignore
![image](https://user-images.githubusercontent.com/96430308/225400236-ac994269-0539-42ee-a774-651d6507566c.png)

Nesses dois ultimos casos, a o ts ignore é porque o queryParams esta tipado como {} sem dizer o que tem dentro dai fica dando erro

2023-03-15 18:15 UTC, fernando-pascoal commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +      {/*@ts-ignore*/}
Foi resolvido

2023-03-15 20:03 UTC, yanguyt requested changes

2023-03-15 20:03 UTC, yanguyt commented on src/modules/shared/hooks/useGetTenantContext/useGetTenantContext.ts
> +    [PixwayAPIRoutes.TENANT_CONTEXT],
```suggestion
    [PixwayAPIRoutes.TENANT_CONTEXT, tenantId],
```

2023-03-15 20:03 UTC, yanguyt commented on src/modules/shared/hooks/useGetTenantInputs/useGetTenantInputsBySlug.ts
> +    [PixwayAPIRoutes.TENANT_INPUTS_BY_SLUG],
```suggestion
    [PixwayAPIRoutes.TENANT_INPUTS_BY_SLUG, companyId],
```

2023-03-15 21:31 UTC, yanguyt approved these changes

2023-03-15 21:41 UTC, rafaelmhp approved these changes

2023-03-15 21:41 UTC, merged