feat: add support for nested tabs on header
TropixInc/w3block-ui-sdk pull request #162
Opened 2023-03-22 19:48 UTC by douglasselias

2023-03-23 14:07 UTC, yanguyt requested changes

2023-03-23 14:07 UTC, yanguyt commented on src/modules/shared/components/HeaderPixwaySDK/HeaderPixwaySDK.tsx
> +  const tabsToPass = defaultTabs?.map(mapOptionsToTabs);
Eu acho que isso vai dar problema.... quando tabs vier como props sem ser do constructor isso não vai funcionar pois ele ja vira da forma correta
```suggestion
  const tabsToPass = tabs ? tabs : defaultTabs?.map(mapOptionsToTabs);
```

2023-03-23 16:16 UTC, douglasselias commented on src/modules/shared/components/HeaderPixwaySDK/components/NavigationTabsPixwaySDK/components/NavigationTabsPixwaySDKDesktop.tsx
> +                      pw-border pw-border-black pw-border-solid
coloquei como black pra ficar mais destacado o pop up, vou deixar sem borda por enquanto.

2023-03-23 16:25 UTC, douglasselias commented on src/modules/shared/components/HeaderPixwaySDK/components/NavigationTabsPixwaySDK/components/NavigationTabsPixwaySDKMobile.tsx
> +                      <ChevronRight className="pw-w-4 pw-h-4" />
aqui está certo.
o chevron fechado está na direita: 
![image](https://user-images.githubusercontent.com/11854050/227268933-8b6a0d86-7681-4c4b-b4f2-bc5b7e8634ed.png)
e aberto está na esquerda:
![image](https://user-images.githubusercontent.com/11854050/227269000-6a74e7a2-f9c9-4ba8-b359-360a36c46476.png)

o Rafa mostrou o menu da americanas, e eles usam desse jeito: 
![image](https://user-images.githubusercontent.com/11854050/227269990-d0ff0f1f-e044-42e7-99b7-b794a8101fb5.png)

2023-03-23 17:16 UTC, gislainy commented on src/modules/shared/components/HeaderPixwaySDK/HeaderPixwaySDK.tsx
> +export const mapOptionsToTabs = (item: any): NavigationTabsPixwaySDKTabs => {
```suggestion
export const mapOptionsToTabs = (item: {label: string; value: string}): NavigationTabsPixwaySDKTabs => {
```

2023-03-23 17:17 UTC, gislainy commented on src/modules/shared/components/HeaderPixwaySDK/HeaderPixwaySDK.tsx
> +    tabs: item.tabs.map((t: any) => ({ name: t.label, router: t.value })),
```suggestion
    tabs: item.tabs.map((t: {label: string; value: string}) => ({ name: t.label, router: t.value })),
```

2023-03-30 12:55 UTC, yanguyt requested changes

2023-03-30 12:55 UTC, yanguyt commented on src/modules/shared/components/HeaderPixwaySDK/HeaderPixwaySDK.tsx
> +export const mapOptionsToTabs = (item: any): NavigationTabsPixwaySDKTabs => {
Alem do mais essa função ela é especifica para o uso do header para o storefront, não faz sentido estar dentro do HeaderPixway... lembrando o headerPixway é usado por outros projetos então tudo que chega nele ja tem que estar mastigado essa função é um adapter exclusivo do Header do storefront

2023-03-31 12:06 UTC, merged