TK-1134 - Include edition in My Profile
TropixInc/w3block-ui-sdk pull request #190
Opened 2023-05-02 19:52 UTC by fernando-pascoal

2023-05-02 21:30 UTC, gislainy commented on public/locales/pt-BR/common.json
> +  "auth>formCompletKYCWithoutLayout>notEditInfos": "Não é possivel editar as informações pois este usuário já foi revisado"
```suggestion
  "auth>formCompletKYCWithoutLayout>notEditInfos": "Não é possivel editar as informações, pois este usuário já foi revisado"
```

2023-05-02 21:32 UTC, gislainy commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +      {reasons?.data?.items[0]?.logs?.at(-1)?.reason &&
```suggestion
      {reasons?.data?.items?.[0]?.logs?.at(-1)?.reason &&
```

2023-05-02 21:36 UTC, gislainy commented on src/modules/shared/components/MyProfileTemplate/MyProfileTemplate.tsx
> +      const contexts = tenantContext?.data?.items.filter(
```suggestion
      const contexts = tenantContext?.data?.items?.filter(
```

2023-05-02 21:37 UTC, gislainy commented on src/modules/shared/components/MyProfileTemplate/MyProfileTemplate.tsx
> +}
```suggestion

{

```

2023-05-02 21:39 UTC, gislainy commented on src/modules/storefront/hooks/useGetTheme/useGetTheme.tsx
> +      setHref('https://foodbusters.stg.w3block.io/');
????

2023-05-09 17:58 UTC, rafaelmhp requested changes

2023-05-09 17:58 UTC, rafaelmhp commented on public/locales/en/common.json
> +  "auth>formCompletKYCWithoutLayout>notEditInfos": "It is not possible to edit the information as this user has already been reviewed"
Your data has already been reviewed and approved. Please contact support if you need to update your information.

2023-05-09 17:58 UTC, rafaelmhp commented on public/locales/pt-BR/common.json
>  }
Seus dados já foram revisados e aprovados. Por favor, contate o suporte técnico se você precisa atualizar suas informações.

2023-05-09 17:58 UTC, rafaelmhp commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +              refer={dynamicMethods.register('inputId')}
tirar?

2023-05-09 17:58 UTC, rafaelmhp commented on src/modules/auth/templates/CompleteKYCTemplateSDK/CompleteKYCTemplateSDK.tsx
> +  ) : profile && profile?.data?.kycStatus !== KycStatus.NoRequired ? (
Verificar cenários em que:
1 - nao existe KYC para o tenant;
2 - nao existe KYC com campos obrigatorios para o tenant;
3 - existe KYC para o tenant;

2023-05-09 17:58 UTC, rafaelmhp commented on src/modules/shared/components/MyProfileTemplate/MyProfileTemplate.tsx
> +                            KYC - {context?.slug}
Remover "KYC - ", usar apenas:
"Informações Complementares" {context?.description}

2023-05-16 14:38 UTC, yanguyt requested changes

2023-05-16 14:38 UTC, yanguyt commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/FormCompleteKYCWithoutLayout.tsx
> +    if (tenantInputs?.data && tenantInputs?.data?.length < 1) {
```suggestion
    if (tenantInputs?.data && !tenantInputs?.data?.length) {
```

2023-05-16 16:58 UTC, yanguyt approved these changes

2023-05-16 17:44 UTC, rafaelmhp approved these changes

2023-05-16 19:32 UTC, merged