feat(pe-64): modal resend email
TropixInc/w3block-ui-sdk pull request #24
Opened 2022-09-12 12:02 UTC by schleu

2022-09-15 13:48 UTC, Percegaroli requested changes

2022-09-15 13:50 UTC, Percegaroli commented on src/modules/shared/components/ModalBlockedAction/ModalBlockedAction.tsx
> +  //const { minutesResendEmail } = useContext(W3blockUISdkResendConfirmEmail);
Pode remover esse comentario? acredito que esquecemos ontem

2022-09-16 17:53 UTC, Percegaroli commented on src/modules/auth/api/requestConfirmationEmail/requestConfirmationEmail.ts
> +};
Conforme conversado via discord, aguardando remoção do arquivo, já que não vai ser mais utilizado

2022-09-26 18:42 UTC, yanguyt approved these changes

2022-09-26 18:42 UTC, yanguyt commented on src/modules/shared/components/ModalBlockedAction/ModalBlockedAction.tsx
> +  }, [countdownDate, setNewCountdown]);
Não precisa rastrear o setNewCountdown

2022-09-27 16:59 UTC, merged