TK-1232 - Create input image for KYC
TropixInc/w3block-ui-sdk pull request #263
Opened 2024-01-24 16:37 UTC by fernando-pascoal

2024-01-25 18:48 UTC, rafaelmhp requested changes

2024-01-25 18:48 UTC, rafaelmhp commented on src/modules/auth/components/FormCompleteKYCWithoutLayout/teste.html
> +<div style="font-size: 13px; display: flex; flex-direction: column; justify-content: center; align-items: center;">
Não deveria remover esse arquivo?

2024-01-25 18:48 UTC, rafaelmhp commented on src/modules/shared/components/SmartInputs/InputImage/InputImage.tsx
> +    if (isSuccess && data && assets?.data?.id) {
Onde está o tratamento para o caso de erro? O usuário consegue ver uma mensagem e re-tentar o upload?

2024-01-26 15:16 UTC, fernando-pascoal commented on src/modules/shared/components/SmartInputs/InputImage/InputImage.tsx
> +    if (isSuccess && data && assets?.data?.id) {
![image](https://github.com/TropixInc/w3block-ui-sdk/assets/96430308/ac3cadba-06bc-482a-b564-d9e2e3818cfe)

O feedback de erro vem desse container que a gente usa em quase todos os inputs

2024-02-01 15:46 UTC, closed without merging