feat(tk-662): pass token page
TropixInc/w3block-ui-sdk pull request #54
Opened 2022-10-04 17:17 UTC by schleu

2022-10-05 16:29 UTC, yanguyt requested changes

2022-10-05 16:29 UTC, yanguyt commented on src/modules/tokens/components/PassTemplate/PassTemplate.tsx
> +const Button = ({
Ja existe um componente de button precisa mesmo criar esse?

2022-10-05 16:29 UTC, yanguyt commented on src/modules/tokens/components/PassTemplate/PassTemplate.tsx
> +          <DetailToken
Eu sei que esses detalhes vao vir da api e tal e que voce vai fazer um map, mas tem como fazer esse map agora criando um array na mão... eu falo isso puramente para diminuir peso do SDK

2022-10-05 16:29 UTC, yanguyt commented on src/modules/tokens/components/PassTemplate/TokenUsageTime.tsx
> +          hours: countDown.hours,
Aqui vale perguntar para a galera de produto se por exemplo a hora for == 0 se vai mostrar ou não

2022-10-05 16:30 UTC, yanguyt approved these changes
Da uma olhadinha nos comentarios e vê se faz sentido... vou deixar aprovado

2022-10-05 19:12 UTC, schleu commented on src/modules/tokens/components/PassTemplate/PassTemplate.tsx
> +const Button = ({
O PixwayButton e o AuthButton não se tem o css bem diferente, dai criei esse interno apenas para não repetir o css em 2 butões.

2022-10-10 12:39 UTC, yanguyt approved these changes

2022-10-11 12:28 UTC, merged