feat(np-11): pass tags and bottons
TropixInc/w3block-ui-sdk pull request #58
Opened 2022-10-08 02:48 UTC by schleu

2022-10-10 19:32 UTC, yanguyt requested changes

2022-10-10 19:32 UTC, yanguyt commented on src/modules/shared/components/PrimaryButton/PrimaryButton.tsx
> +export const PrimaryButton = ({
Não vejo necessidade de ter dois arquivos de botao para alterar somente a cor... eles podiam ser somente um

2022-10-10 19:32 UTC, yanguyt commented on src/modules/shared/components/PrimaryButton/PrimaryButton.tsx
> +  return classNames(
Eu particularmente não gosto muito desse formato, pois prejudica muito a customização por parte do cliente. tendo em vista que ele teria algumas opções de uso do botao somente.
Outro ponto, tem algumas classes que estao como !important é isso mesmo?

2022-10-10 19:32 UTC, yanguyt commented on src/modules/shared/components/SecondaryButton/SecondaryButton.tsx
> +export const SecondaryButton = ({
No primary estão minhas duvidas

2022-10-10 19:32 UTC, yanguyt commented on src/modules/tokens/components/TokensListTemplate/TokensListTemplate.tsx
> +              hasActived={index % 2 === 0}
hasActivated

2022-10-10 19:32 UTC, yanguyt commented on src/modules/tokens/components/WalletTokenCard/WalletTokenCard.tsx
> +  hasActived?: boolean;
hasActivated

2022-10-10 19:32 UTC, yanguyt commented on src/modules/tokens/components/WalletTokenCard/WalletTokenCard.tsx
> +  hasActived,
hasActivated

2022-10-10 19:32 UTC, yanguyt commented on src/modules/tokens/components/WalletTokenCard/WalletTokenCard.tsx
> +          cardClassName,
nesse caso se o usuário colocar algo aqui que tenha a ver com o que foi declarado de calsse em baixo não vai ter efeito nenhum...
recomendo inverter ordem

2022-10-10 19:32 UTC, yanguyt commented on src/modules/tokens/components/WalletTokenCard/WalletTokenCard.tsx
>  const cardClassName =
porque está setado aqui? existe alguma justificativa para isso?

2022-10-10 19:32 UTC, yanguyt commented on src/modules/tokens/components/WalletTokenCard/WalletTokenCard.tsx
>  const descriptionContainerClassName =
mesma coisa do cardClassName

2022-10-10 19:32 UTC, yanguyt commented on src/modules/tokens/components/WalletTokenCard/WalletTokenCard.tsx
> +                <div className="pw-text-[#295BA6] pw-text-[12px] pw-leading-[18px] pw-font-bold pw-bg-[#E5EDF9] pw-border pw-border-[#295ba67f] pw-rounded-full pw-absolute pw-left-[13px] pw-top-[14px
Verificar se essas cores não tem de estar conectadas com o brand-primary... foodbusters seria dourado e o primesea azul por exemplo... falar com a galera de produto

2022-10-10 19:32 UTC, yanguyt commented on src/modules/tokens/components/WalletTokenCard/WalletTokenCard.tsx
> +            hasActived ? (
hasActivated

2022-10-10 19:32 UTC, yanguyt commented on src/modules/tokens/components/WalletTokenCard/WalletTokenCard.tsx
> +              <PrimaryButton width="small">Utilizar Pass</PrimaryButton>
faltou o translate

2022-10-10 19:32 UTC, yanguyt commented on src/modules/tokens/components/WalletTokenCard/WalletTokenCard.tsx
> +              <SecondaryButton width="small">Visualizar Pass</SecondaryButton>
faltou o translate

2022-10-10 19:32 UTC, yanguyt commented on src/modules/tokens/components/WalletTokenCard/WalletTokenCard.tsx
> +            <Pointer />
Aqui voce pode utilixar o Array(3).fill().map(() => <Pointer/>)

2022-10-14 10:59 UTC, schleu commented on src/modules/shared/components/PrimaryButton/PrimaryButton.tsx
> +  return classNames(
Parece que tem uma classe sobreescrevendo o css de button, então sim, precisa do important.

2022-10-14 11:36 UTC, schleu commented on src/modules/shared/components/PrimaryButton/PrimaryButton.tsx
> +  return classNames(
Não é exatamente mudança de cor, tem um shadow também, borda...

2022-10-14 13:23 UTC, yanguyt requested changes
Acho que ficou faltando algumas coisas

2022-10-14 13:24 UTC, yanguyt reviewed
vi aqui que ainda nao foi para code review foi mal

2022-10-18 12:56 UTC, yanguyt approved these changes

2022-10-18 12:56 UTC, yanguyt commented on src/modules/tokens/components/TokensListTemplate/TokensListTemplate.tsx
> +  const isDevelopment = !isProduction;
Isso daqui não faz sentido... 
onde usa isDevelopment é só colocar !isProduction

2022-10-18 12:56 UTC, yanguyt commented on src/modules/tokens/components/TokensListTemplate/TokensListTemplate.tsx
> +    useGetNFTSByWallet(wallet?.chainId || 0);
coloca cono default 80001

2022-10-18 12:56 UTC, yanguyt commented on src/modules/tokens/components/TokensListTemplate/TokensListTemplate.tsx
> +        ethNFTsResponse.data.items.map((nft) => mapNFTToToken(nft, 80001))
Esse 80001 ta certo aqui nessa função de mapNFTToToken?
até mesmo esse token é necessário tambem? tendo em vista que só vai fazer uma chamada agora

2022-10-18 17:59 UTC, schleu commented on src/modules/tokens/components/TokensListTemplate/TokensListTemplate.tsx
> +        ethNFTsResponse.data.items.map((nft) => mapNFTToToken(nft, 80001))
Precisa para poder organizar os dados, para fazer a chamada de alguns componentes...

2022-10-19 12:39 UTC, yanguyt approved these changes

2022-10-19 13:26 UTC, merged